// app/frontend-solid/src/components/hmm/SettingsDirItem.tsx
import { EditIcon } from "lucide-solid";
import { Button } from "../ui/button";
import { GoPref, usePreferenceSignal } from "@/data/prefs";
import { GetExportDirectory } from "wailsjs/go/main/App";
import { Accessor, ComponentProps, createMemo } from "solid-js";

export function SettingsDirItem(
  props: {
    name: string;
    path: string;
    onEditClick?: () => void;
  } & ComponentProps<"div">
) {
  const pathname = createMemo(() =>
    props.path.length > 0 ? props.path : "unset"
  );

  return (
    <div
      class="flex flex-row justify-between items-center m-2 hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50"
      {...props}
    >
      <div class="flex flex-col m-2">
        <h2 class="space-y-1 text-primary">{props.name}</h2>
        <div class="text-foreground/75">{pathname()}</div>
      </div>
      {props.onEditClick ? (
        <Button size="icon" class="mx-2" onPointerDown={props.onEditClick}>
          <EditIcon />
        </Button>
      ) : undefined}
    </div>
  );
}

export function DirUpdate({
  pref,
  title,
  ...rest
}: {
  pref: GoPref<string>;
  title: string;
} & ComponentProps<"div">) {
  const [dir, setDir] = usePreferenceSignal("", pref);

  const openDirectoryDialog = async () => {
    const dir = await GetExportDirectory();

    if (dir) {
      setDir(dir);
    }
  };

  return (
    <SettingsDirItem
      name={title}
      onEditClick={openDirectoryDialog}
      path={dir()}
      {...rest}
    />
  );
}

// frontend/src/components/SettingsDirItem.tsx
import { Button } from "./ui/button";

export function SettingsDirItem(props: {
    name: string;
    setDir?: (() => void);
    dir: string | undefined;
}) {
    return (
        <div className="flex flex-row justify-between items-center m-2 rounded-lg hover:bg-primary-foreground">
            <div className="flex flex-col m-2">
                <h2 className="space-y-1 text-primary">{props.name}</h2>
                <div className="text-zinc-500">{props.dir?.ifEmpty(() => "unset")}</div>
            </div>
            {props.setDir ?
                <Button size="icon" className="mx-2" onPointerDown={props.setDir}>
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        height="24px"
                        viewBox="0 -960 960 960"
                        width="24px"
                    >
                        <path d="M200-200h57l391-391-57-57-391 391v57Zm-80 80v-170l528-527q12-11 26.5-17t30.5-6q16 0 31 6t26 18l55 56q12 11 17.5 26t5.5 30q0 16-5.5 30.5T817-647L290-120H120Zm640-584-56-56 56 56Zm-141 85-28-29 57 57-29-28Z" />
                    </svg>
                </Button> : undefined
            }
        </div>
    );
}
