// app/frontend-solid/src/index.tsx
/* @refresh reload */
import "./index.css";

import { render } from "solid-js/web";

import App from "./app";
import { Navigate, Route, Router } from "@solidjs/router";
import {
  GenshinScreen,
  StarRailScreen,
  WuWaScreen,
  ZZZScreen,
} from "./pages/GameScreen";
import { SettingsScreen } from "./pages/SettingsScreen";
import { ModIndexPage } from "./pages/Mod/ModIndexScreen";
import { ModViewScreen } from "./pages/Mod/ModViewScreen";
import { ModBrowseScreen } from "./pages/Mod/ModBrowseScreen";

const root = document.getElementById("root");

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    "Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?"
  );
}

render(
  () => (
    <Router root={App}>
      <Route path={"/"} component={() => <Navigate href={"/genshin"} />} />
      <Route path={"/genshin"} component={GenshinScreen} />
      <Route path={"/starrail"} component={StarRailScreen} />
      <Route path={"/zenless"} component={ZZZScreen} />
      <Route path={"/wuwa"} component={WuWaScreen} />
      <Route path={"/settings"} component={SettingsScreen} />
      <Route path="mods" component={ModIndexPage}>
        <Route path=":id" component={ModViewScreen} />
        <Route path="cats/:id" component={ModBrowseScreen} />
      </Route>
    </Router>
  ),
  root!
);

// frontend/src/main.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'
import GameScreen from './screens/GameScreen.tsx';
import { GenshinApi, StarRailApi } from './data/dataapi.ts';
import { createHashRouter, RouterProvider, useNavigate, useRouteError } from 'react-router-dom';
import ModBrowseScreen from './screens/ModBrowseScreen.tsx';
import { ModViewScreen } from './screens/ModViewScreen.tsx';
import { Button } from './components/ui/button.tsx';
import { ModIndexPage } from './screens/ModIndexPage.tsx';
import SettingsScreen from './screens/SettingsScreen.tsx';
const router = createHashRouter([
  {
    path: "/",
    element: <App />,
    children: [
      {
        path: "genshin",
        element: <GameScreen dataApi={GenshinApi}/>,
      },
      {
        path: "starrail",
        element: <GameScreen dataApi={StarRailApi}/>,
      },
      {
        path: "zenless",
        element: <GameScreen dataApi={StarRailApi}/>,
      },
      {
        path: "wuwa",
        element: <GameScreen dataApi={StarRailApi}/>,
      },
      {
        path: "playlist",
        element: <></>,
      },
      {
        path: "settings",
        element: <SettingsScreen />
      },
      {
        path: "mods",
        element: <ModIndexPage />,
        children: [
          {
            path: ":id",
            element:  <ModViewScreen />
          },
          {
            path: "cats/:id",
            element: <ModBrowseScreen />
          },
        ]
      }
    ],
    errorElement: <ErrorPage />,
  },
]);


ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>,
)

export default function ErrorPage() {

  const error: any = useRouteError();
  const navigate = useNavigate();

  return (
    <div className="flex flex-col items-center justify-center w-full">
      <h1>Oops!</h1>
      <p>Sorry, an unexpected error has occurred.</p>
      <p>
        <i>{error.statusText || error.message}</i>
      </p>
      <Button onClick={() => navigate("/genshin")}>Home</Button>
    </div>
  );
}
